config/routes.rb
Rails.application.routes.draw do
  resources :heart_zones
  get 'pages/index'
  devise_for :users
  root to: 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/heart_zone.rb
class HeartZone < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/heart_zones_controller.rb
class HeartZonesController < ApplicationController
  before_action :set_heart_zone, only: [:show, :edit, :update, :destroy]

  # GET /heart_zones
  # GET /heart_zones.json
  def index
    @heart_zones = HeartZone.all
  end

  # GET /heart_zones/1
  # GET /heart_zones/1.json
  def show
  end

  # GET /heart_zones/new
  def new
    @heart_zone = HeartZone.new
  end

  # GET /heart_zones/1/edit
  def edit
  end

  # POST /heart_zones
  # POST /heart_zones.json
  def create
    @heart_zone = HeartZone.new(heart_zone_params)

    respond_to do |format|
      if @heart_zone.save
        format.html { redirect_to @heart_zone, notice: 'Heart zone was successfully created.' }
        format.json { render :show, status: :created, location: @heart_zone }
      else
        format.html { render :new }
        format.json { render json: @heart_zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heart_zones/1
  # PATCH/PUT /heart_zones/1.json
  def update
    respond_to do |format|
      if @heart_zone.update(heart_zone_params)
        format.html { redirect_to @heart_zone, notice: 'Heart zone was successfully updated.' }
        format.json { render :show, status: :ok, location: @heart_zone }
      else
        format.html { render :edit }
        format.json { render json: @heart_zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heart_zones/1
  # DELETE /heart_zones/1.json
  def destroy
    @heart_zone.destroy
    respond_to do |format|
      format.html { redirect_to heart_zones_url, notice: 'Heart zone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_heart_zone
      @heart_zone = HeartZone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def heart_zone_params
      params.require(:heart_zone).permit(:maxhr, :rhravg, :illness, :drugs, :age, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heart_zones_helper.rb
module HeartZonesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/heart_zones/_form.html.haml
= form_for @heart_zone do |f|
  - if @heart_zone.errors.any?
    #error_explanation
      %h2= "#{pluralize(@heart_zone.errors.count, "error")} prohibited this heart_zone from being saved:"
      %ul
        - @heart_zone.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :maxhr
    = f.number_field :maxhr
  .field
    = f.label :rhravg
    = f.number_field :rhravg
  .field
    = f.label :illness
    = f.check_box :illness
  .field
    = f.label :drugs
    = f.check_box :drugs
  .field
    = f.label :age
    = f.number_field :age
  .field
    = f.label :user
    = f.text_field :user
  .actions
    = f.submit 'Save'

app/views/heart_zones/edit.html.haml
%h1 Editing heart_zone

= render 'form'

= link_to 'Show', @heart_zone
\|
= link_to 'Back', heart_zones_path

app/views/heart_zones/index.html.haml
%h1 Listing heart_zones

%table
  %thead
    %tr
      %th Maxhr
      %th Rhravg
      %th Illness
      %th Drugs
      %th Age
      %th User
      %th
      %th
      %th

  %tbody
    - @heart_zones.each do |heart_zone|
      %tr
        %td= heart_zone.maxhr
        %td= heart_zone.rhravg
        %td= heart_zone.illness
        %td= heart_zone.drugs
        %td= heart_zone.age
        %td= heart_zone.user
        %td= link_to 'Show', heart_zone
        %td= link_to 'Edit', edit_heart_zone_path(heart_zone)
        %td= link_to 'Destroy', heart_zone, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Heart zone', new_heart_zone_path

app/views/heart_zones/new.html.haml
%h1 New heart_zone

= render 'form'

= link_to 'Back', heart_zones_path

app/views/heart_zones/show.html.haml
%p#notice= notice

%p
  %b Maxhr:
  = @heart_zone.maxhr
%p
  %b Rhravg:
  = @heart_zone.rhravg
%p
  %b Illness:
  = @heart_zone.illness
%p
  %b Drugs:
  = @heart_zone.drugs
%p
  %b Age:
  = @heart_zone.age
%p
  %b User:
  = @heart_zone.user

= link_to 'Edit', edit_heart_zone_path(@heart_zone)
\|
= link_to 'Back', heart_zones_path

app/views/layouts/_messages.html.haml
= current_user.email

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content=> "width=device-width, initial-scale=1, shrink-to-fit=no"}
    %title Get Your Pace
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{:href => "https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css", :rel => "stylesheet", :integrity => "sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4", :crossorigin => "anonymous"}/
    -#%link{:href => "//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css", :rel => "stylesheet"}/
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      = render 'layouts/navigation'
      %main{:role => "main"}
      = render 'layouts/messages'
      = yield
      -# Optional JavaScript
      -# jQuery first, then Popper.js, then Bootstrap JS -->
      %script{:src => "https://code.jquery.com/jquery-3.3.1.slim.min.js", :integrity => "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo", :crossorigin => "anonymous"}/
      %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js", :integrity => "sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ", :crossorigin => "anonymous"}/
      %script{:src => "https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js", :integrity=>"sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm", :crossorigin=>"anonymous"}

app/views/pages/index.html.haml
%h1 Pages#index
%p Find me in app/views/pages/index.html.erb

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/